### PR TITLE
Report errors on CI

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by esteve** [comment]
@mitsudome-r these changes make CI fail when the tests don't pass. Given that fixing the tests is trivial, I'll go ahead and fix them so you can review the fixes.

**Comment by esteve** [comment]
The two PR that fix the issues are:

https://github.com/tier4/Pilot.Auto/pull/73

https://github.com/tier4/Pilot.Auto/pull/74

**Comment by mitsudome-r** [comment]
#73 and #74 are now merged. Please rebase to newest ros2 branch.

**Comment by esteve** [comment]
This PR now passes, so I'm going to merge it so that subsequent PR get tested on the CI.

**Pull request merged**
