### PR TITLE
Add linters to obstacle_avoidance_planner

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Review by nnmm — APPROVED** [review]
LGTM – did you run clang-tidy as well?

**Comment by esteve** [comment]
@nnmm yes. Perhaps we should add `ament_clang_tidy` as a linter, what do you think?

**Comment by esteve** [comment]
@nnmm I just realized that the linters use the wrong packages (e.g. ament_cmake_cpplint instead of ament_cpplint). Fixed in https://github.com/tier4/Pilot.Auto/pull/158/commits/5219ce16cf90ef03551b83f40049ec69ea880bf6

**Comment by nnmm** [comment]
Isn't ament_cmake_cpplint what we want? Also, ament_cmake_tidy didn't work for me, hence the manual approach.

**Comment by esteve** [comment]
@nnmm according to this https://github.com/ament/ament_lint/blob/master/ament_lint_auto/doc/index.rst, it's `ament_cppcheck`

**Comment by jilaada** [comment]
@esteve @nnmm I couldn't get `ament_cppcheck` to work by itself, no tests were actually run. I needed to change it to `ament_cmake_cppcheck`.

**Comment by esteve** [comment]
@jilaada you're right, `ament_cmake_cppcheck` is the correct one https://github.com/ament/ament_lint/blob/master/ament_cmake_cppcheck/doc/index.rst#how-to-run-the-check-from-within-a-cmake-ament-package-as-part-of-the-tests I'll file a ticket upstream to update the https://github.com/ament/ament_lint/blob/master/ament_lint_auto/doc/index.rst

**Comment by esteve** [comment]
I've submitted https://github.com/ament/ament_lint/pull/278 upstream and https://github.com/tier4/AutowareArchitectureProposal/pull/144 to the porting guide.

**Review by jilaada — APPROVED** [review]
LGTM :+1:

**Pull request merged**
