### PR TITLE
Add topic_tools to build_depend.repos

### PR DESCRIPTION
**Pull request by jilaada**
Add the dependencies to fix CI failure in #101 and (possibly) #51

### CODE REVIEW

**Comment by jilaada** [comment]
Looks like the copyright check is failing on `topic_tools` 
```
1: Test command: /usr/bin/python3 "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/__w/Pilot.Auto/Pilot.Auto/build/topic_tools/test_results/topic_tools/copyright.xunit.xml" "--package-name" "topic_tools" "--output-file" "/__w/Pilot.Auto/Pilot.Auto/build/topic_tools/ament_copyright/copyright.txt" "--command" "/opt/ros/foxy/bin/ament_copyright" "--xunit-file" "/__w/Pilot.Auto/Pilot.Auto/build/topic_tools/test_results/topic_tools/copyright.xunit.xml"
1: Test timeout computed to be: 60
1: -- run_test.py: invoking following command in '/__w/Pilot.Auto/Pilot.Auto/dependency_ws/vendor/topic_tools':
1:  - /opt/ros/foxy/bin/ament_copyright --xunit-file /__w/Pilot.Auto/Pilot.Auto/build/topic_tools/test_results/topic_tools/copyright.xunit.xml
1: CONTRIBUTING.md: file not found
1: LICENSE: file not found
1: 2 errors, checked 3 files
1: -- run_test.py: return code 1
1: -- run_test.py: verify result file '/__w/Pilot.Auto/Pilot.Auto/build/topic_tools/test_results/topic_tools/copyright.xunit.xml'
1/6 Test #1: copyright ........................***Failed    0.31 sec
```

Likewise with `rclcpp_generic`:
```
test 3
    Start 3: copyright

3: Test command: /usr/bin/python3 "-u" "/opt/ros/foxy/share/ament_cmake_test/cmake/run_test.py" "/__w/Pilot.Auto/Pilot.Auto/build/rclcpp_generic/test_results/rclcpp_generic/copyright.xunit.xml" "--package-name" "rclcpp_generic" "--output-file" "/__w/Pilot.Auto/Pilot.Auto/build/rclcpp_generic/ament_copyright/copyright.txt" "--command" "/opt/ros/foxy/bin/ament_copyright" "--xunit-file" "/__w/Pilot.Auto/Pilot.Auto/build/rclcpp_generic/test_results/rclcpp_generic/copyright.xunit.xml"
3: Test timeout computed to be: 60
3: -- run_test.py: invoking following command in '/__w/Pilot.Auto/Pilot.Auto/dependency_ws/vendor/rclcpp_generic':
3:  - /opt/ros/foxy/bin/ament_copyright --xunit-file /__w/Pilot.Auto/Pilot.Auto/build/rclcpp_generic/test_results/rclcpp_generic/copyright.xunit.xml
3: CONTRIBUTING.md: file not found
3: LICENSE: file not found
3: 2 errors, checked 12 files
3: -- run_test.py: return code 1
3: -- run_test.py: verify result file '/__w/Pilot.Auto/Pilot.Auto/build/rclcpp_generic/test_results/rclcpp_generic/copyright.xunit.xml'
3/7 Test #3: copyright ........................***Failed    0.31 sec
```

**Comment by nnmm** [comment]
I think I might need to add `set(ament_cmake_copyright_FOUND TRUE)` to CMakeLists.txt. Let me check if that's what other packages do too.

**Comment by esteve** [comment]
@nnmm adding a LICENSE and CONTRIBUTING.md file should be enough. Given that the `rclcpp_generic` package is Apache 2.0, it's in fact required by the license to add at least the LICENSE file, I think.

**Comment by nnmm** [comment]
@esteve Other packages in `https://github.com/ros2/rclcpp` do not have a `CONTRIBUTING.md` or `LICENSE` file either, but they also don't do anything special in `CMakeLists.txt`. They're Apache 2.0 too. Why don't they fail this test?

**Comment by esteve** [comment]
@nnmm my theory is that `ament_copyright` crawls the root directory of a repository, and those two files are in in fact in the https://github.com/ros2/rclcpp root

**Comment by nnmm** [comment]
@jilaada You can try the `autoware` branch of those repos instead of the commit SHAs, I added the two files there

**Comment by nnmm** [comment]
@esteve The discrepancy exists even when I put the `rclcpp_generic` directory next to `rclcpp_action` etc. The only explanation I can think of would be that this copyright check parses the `QUALITY_DECLARATION.md` which references those files. But that seems strange since it seems to be meant for humans.

**Comment by esteve** [comment]
@jilaada I hope you don't mind, but I thought it might be a bit late in Japan now, so I pushed the changes that @nnmm did in https://github.com/tier4/AutowareArchitectureProposal/pull/122 Hope that's ok with you.

**Comment by jilaada** [comment]
> @jilaada I hope you don't mind, but I thought it might be a bit late in Japan now, so I ported the changes that @nnmm did in https://github.com/tier4/AutowareArchitectureProposal/pull/122 to this PR and pushed them to your fork. Hope that's ok with you.

No worries! Thanks for making those changes! 👍 

Feel free to merge as well once the CI passes

**Review by esteve — APPROVED** [review]

**Pull request merged**
