### PR TITLE
adding linters to ndt

### PR DESCRIPTION
**Pull request by nik-tier4**

### CODE REVIEW

**Review by jilaada — COMMENTED** [review]
I ran the linter tests with no problems however clang-tidy outputted some errors in header files:
```
/home/jilada/AutowareArchitectureProposal/src/autoware/autoware.iv/localization/pose_estimator/ndt_scan_matcher/ndt/include/ndt/impl/base.hpp:19:1: error: no template named 'NormalDistributionsTransformBase' [clang-diagnostic-error]
NormalDistributionsTransformBase<PointSource, PointTarget>::NormalDistributionsTransformBase()
^
/home/jilada/AutowareArchitectureProposal/src/autoware/autoware.iv/localization/pose_estimator/ndt_scan_matcher/ndt/include/ndt/impl/omp.hpp:19:1: error: no template named 'NormalDistributionsTransformOMP' [clang-diagnostic-error]
NormalDistributionsTransformOMP<PointSource, PointTarget>::NormalDistributionsTransformOMP()
^
/home/jilada/AutowareArchitectureProposal/src/autoware/autoware.iv/localization/pose_estimator/ndt_scan_matcher/ndt/include/ndt/impl/pcl_generic.hpp:19:1: error: no template named 'NormalDistributionsTransformPCLGeneric' [clang-diagnostic-error]
NormalDistributionsTransformPCLGeneric<
^
/home/jilada/AutowareArchitectureProposal/src/autoware/autoware.iv/localization/pose_estimator/ndt_scan_matcher/ndt/include/ndt/impl/pcl_modified.hpp:19:1: error: no template named 'NormalDistributionsTransformPCLModified' [clang-diagnostic-error]
NormalDistributionsTransformPCLModified<
^
Found compiler error(s).
```

**Comment by nik-tier4** [comment]
@jilaada fixed the errors, thank you :)

**Comment by jilaada** [comment]
Seems like the build has failed here, @nik-tier4 could you check it out?

**Comment by nik-tier4** [comment]
Looking into it. The error seems to be in ndt_scan_matcher package.

**Review by jilaada — APPROVED** [review]
LGTM, ran against the linters and was able to build upstream packages. Clang-tidy errors are ~~not~~ fixed! Thanks!

**Comment by nik-tier4** [comment]
> LGTM, ran against the linters and was able to build upstream packages. Clang-tidy errors are not fixed! Thanks!

Clang-tidy errors are fixed right?

**Comment by jilaada** [comment]
> > LGTM, ran against the linters and was able to build upstream packages. Clang-tidy errors are not fixed! Thanks!
> 
> Clang-tidy errors are fixed right?

Oh oops, yeah I mean they are fixed! Sorry about that :bowing_woman:

**Pull request merged**
