### PR TITLE
Fix format package xml

### PR DESCRIPTION
**Pull request by esteve**

### CODE REVIEW

**Comment by mitsudome-r** [comment]
colcon build is still having following errors:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 451, in run_check
    return plugin["plugin"](**arguments)
  File "/usr/local/lib/python3.8/dist-packages/flake8/plugins/pyflakes.py", line 99, in __init__
    super(FlakesChecker, self).__init__(
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 497, in __init__
    self.handleChildren(tree)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 1276, in CLASSDEF
    self.handleNode(stmt, node)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 871, in handleNode
    handler(node)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 870, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/usr/local/lib/python3.8/dist-packages/pyflakes/checker.py", line 700, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 682, in _run_checks
    return checker.run_checks()
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 612, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 513, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 456, in run_check
    raise exceptions.PluginExecutionFailed(
  File "/usr/local/lib/python3.8/dist-packages/flake8/exceptions.py", line 86, in __init__
    self.original_exception = kwargs.pop("exception")
KeyError: 'exception'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ros/foxy/bin/ament_flake8", line 11, in <module>
    load_entry_point('ament-flake8==0.9.5', 'console_scripts', 'ament_flake8')()
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_flake8/main.py", line 32, in main
    rc, _ = main_with_errors(argv=argv)
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_flake8/main.py", line 86, in main_with_errors
    report = generate_flake8_report(
  File "/opt/ros/foxy/lib/python3.8/site-packages/ament_flake8/main.py", line 203, in generate_flake8_report
    report.report = style.check_files(paths)
  File "/usr/local/lib/python3.8/dist-packages/flake8/api/legacy.py", line 101, in check_files
    self._application.run_checks(paths)
  File "/usr/local/lib/python3.8/dist-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/usr/local/lib/python3.8/dist-packages/flake8/checker.py", line 302, in run_parallel
    for ret in pool_map:
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
KeyError: 'exception'
```

Any idea how to fix them?

**Comment by esteve** [comment]
@mitsudome-r this looks like an issue in PyFlakes and not colcon (https://github.com/PyCQA/pyflakes/issues/367). What version of pyflakes do you have installed? On Ubuntu 20.04, the version available of python3-pyflakes is 2.1.1, which should fix the issue.

**Comment by mitsudome-r** [comment]
I was running on ade environment.
I installed pyflakes version `2.1.1-2` by `sudo apt install pyflakes`, and re-run test, but it still fails with the same error...

**Comment by esteve** [comment]
@mitsudome-r could you check again after installing `python3-flakes` and `pyflakes3`? I think the `pyflakes` (without a 3) package is for Python 2

**Comment by mitsudome-r** [comment]
I don't know why, but it started to pass in ade now...

**Comment by mitsudome-r** [comment]
I will merge this.

**Review by mitsudome-r — APPROVED** [review]

**Comment by nnmm** [comment]
@esteve I'm getting the `flake8` error again. Did you by chance find out anything new in the meantime?

**Comment by esteve** [comment]
@nnmm in the ros2 branch or in another one?

**Comment by nnmm** [comment]
@esteve Sorry, false alarm. Restarting ade seems to have fixed it, not sure why.

**Pull request merged**
